languageCode = 'en-us'
DefaultContentLanguage = "en"

author = "June Grato"
baseURL = "https://www.bocce.garden/"
copyright = "Copyright © 2022–2022"
enableEmoji = true
disqusShortname = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "G-NNWPSLT9RX"
hasCJKLanguage = false
theme = "hugo-theme-eureka"
title = "bocce.garden"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 1

[params]
  bannerFont = "fonts/exampleFont" 
  description = "places for memories worth keeping" 
  env = "production" # for Google Analytics and DISQUS.
  favicon = "img/favicon-32x32.png" 
  fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
  useChineseFonts = false 
  postDateFormat = "2006-1-2"
  mainSections = ['gardens', 'playthroughs']

[menu]
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  garden = "gardens"
  playthrough = "playthroughs"

[social]
  github = "http://github.com/"
  instagram = ""
  mail = "mailto:vgrato@gmail.com"
  youtube = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

[build]
  useResourceCacheWhen = 'always'
